<div class="row">
    <div class="column">
        <div class="ui breadcrumb">
            <a class="section" href="/account/dashboard">Início</a>
            <div class="divider"> / </div>
            <div class="active section"><?php echo $this->title_page ?></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
        <div class="ui segment">
            <table class="ui celled selectable table" id="onTableAccount">
                <thead>
                    <tr>
                        <th></th>
                        <th>Nome</th>
                        <th>Conta</th>
                        <th>Tipo</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="ui small modal" id="onModalCreate">
    <div class="header">Nova conta</div>
    <div class="content">
        <form class="ui equal width form">
            <div class="fields">
                <div class="field required">
                    <label>Nome</label>
                    <input type="text" name="name_account" />
                </div>
            </div>
            <div class="fields">
                <div class="field required">
                    <label>Tipo</label>
                    <select class="ui dropdown" name="id_account_type">
                        <option value="1">Conta Corrente</option>
                        <option value="2">Conta Poupança</option>
                        <option value="3">Caixa</option>
                        <option value="4">Cartão de Crédito</option>
                    </select>
                </div>
                <div class="field required">
                    <label>Conta</label>
                    <input type="text" name="debit_account" placeholder="Informe..." />
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>

<div class="ui small modal" id="onModalUpdate">
    <div class="header">Atualizar conta</div>
    <div class="content">
        <form class="ui form">
            <div class="fields">
                <div class="field required">
                    <label>Nome</label>
                    <input type="text" name="name_account" />
                </div>
            </div>
            <div class="fields">
                <div class="field required">
                    <label>Tipo</label>
                    <select class="ui dropdown" name="id_account_type">
                        <option value="1">Conta Corrente</option>
                        <option value="2">Conta Poupança</option>
                        <option value="3">Caixa</option>
                        <option value="4">Cartão de Crédito</option>
                    </select>
                </div>
                <div class="field required">
                    <label>Conta</label>
                    <input type="text" name="debit_account" placeholder="Informe..." />
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>