<div class="row">
    <div class="column">
        <div class="ui breadcrumb">
            <a class="section" href="/account/dashboard">Início</a>
            <div class="divider"> / </div>
            <div class="active section"><?php echo $this->title_page ?></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
        <div class="ui segment">
            <table class="ui celled table" id="onTableProjectTask">
                <thead>
                    <tr>
                        <th></th>
                        <th>Nome</th>
                        <th>Status</th>
                        <th>Início</th>
                        <th>Término</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="ui small modal" id="onModalCreate">
    <div class="header">Novo registro</div>
    <div class="content">
        <form class="ui form">
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-2-3@s">
                    <div class="field required">
                        <label>Nome</label>
                        <input type="text" name="name_project_task" />
                    </div>
                </div>
                <div class="uk-width-1-3@s">
                    <label>Status</label>
                    <select class="ui dropdown" name="id_project_task_status">
                        <option value="1">Requisitos</option>
                        <option value="2">Desenvolvimento</option>
                        <option value="3">Teste</option>
                        <option value="4">Concluído</option>
                    </select>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Data (Início)</label>
                        <input type="date" name="date_start_project_task" />
                    </div>
                </div>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Data (Término)</label>
                        <input type="date" name="date_finish_project_task" />
                    </div>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-1@s">
                    <div class="field">
                        <label>Observação</label>
                        <textarea name="observation_project_task"></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>

<div class="ui small modal" id="onModalUpdate">
    <div class="header">Atualizar conta</div>
    <div class="content">
        <form class="ui form">
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-2-3@s">
                    <div class="field required">
                        <label>Nome</label>
                        <input type="text" name="name_project_task" />
                    </div>
                </div>
                <div class="uk-width-1-3@s">
                    <label>Status</label>
                    <select class="ui dropdown" name="id_project_task_status">
                        <option value="1">Requisitos</option>
                        <option value="2">Desenvolvimento</option>
                        <option value="3">Teste</option>
                        <option value="4">Concluído</option>
                    </select>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Data (Início)</label>
                        <input type="date" name="date_start_project_task" />
                    </div>
                </div>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Data (Término)</label>
                        <input type="date" name="date_finish_project_task" />
                    </div>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-1@s">
                    <div class="field">
                        <label>Observação</label>
                        <textarea name="observation_project_task"></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>

<div class="ui small modal" id="onModalDelete">
    <div class="header">Confirmar Exclusão</div>
    <div class="content uk-text-center">
        <p class="uk-text-meta">Você tem certeza que deseja excluir o registro?</p>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Confirmar</button>
    </div>
</div>