<section class="uk-section uk-section-secondary uk-padding-remove">

    <div class="uk-flex uk-flex-center" uk-grid uk-height-viewport>
        <div class="uk-width-large">
            <div class="uk-padding uk-text-center">
                <h1 class="uk-h1">Painel de controle</h1>
            </div>
            <div class="uk-card uk-card-body">
                <form class="ui inverted form" autocomplete="off">
                    <div class="uk-grid-small" uk-grid>
                        <div class="uk-width-1-1">
                            <div class="field required">
                                <label>Usuário</label>
                                <input type="text" name="email_user" placeholder="Informe seu usuário" />
                            </div>
                        </div>
                    </div>
                    <div class="uk-grid-small" uk-grid>
                        <div class="uk-width-1-1">
                            <div class="field required">
                                <label>Senha</label>
                                <input type="password" name="password_user" placeholder="Informe sua senha" />
                            </div>
                        </div>
                    </div>
                    <div class="uk-grid-small" uk-grid>
                        <div class="uk-width-1-1">
                            <div class="field">
                                <button class="ui primary button">Entrar</button>
                            </div>
                        </div>
                    </div>
                </form>
                
                
                <!--<p class="uk-text-meta">Ainda não possui uma conta? <a href="https://api.whatsapp.com/send?phone=5591982970121" target="_blank">Fale conosco</a></p>-->
            </div>
        </div>
    </div>

</section>