<div class="row">
    <div class="column">
        <div class="ui breadcrumb">
            <a class="section" href="/account/dashboard">Início</a>
            <div class="divider"> / </div>
            <div class="active section"><?php echo $this->title_page ?></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
        <div class="ui segment">
            <form class="ui equal width form on-form-company">
                <div class="fields">
                    <div class="field disabled">
                        <label>Documento (CNPJ)</label>
                        <input type="text" name="document_company" class="on-mask-cnpj" disabled />
                    </div>
                </div>
                <div class="fields">
                    <div class="field disabled">
                        <label>Razão social</label>
                        <input type="text" name="name_company" disabled />
                    </div>
                    <div class="field disabled">
                        <label>Nome fantasia</label>
                        <input type="text" name="nickname_company" disabled />
                    </div>
                </div>
                <hr class="ui divider" />
                <div class="fields">
                    <div class="field disabled">
                        <label>CEP</label>
                        <input type="text" name="zipcode_company" disabled />
                    </div>
                </div>
                <div class="fields">
                    <div class="field disabled">
                        <label>Endereço</label>
                        <input type="text" name="public_place_company" disabled />
                    </div>
                    <div class="field disabled">
                        <label>Número</label>
                        <input type="text" name="number_company" disabled />
                    </div>
                </div>
                <div class="fields">
                    <div class="field disabled">
                        <label>Complemento</label>
                        <input type="text" name="complament_company" disabled />
                    </div>
                </div>
                <div class="fields">
                    <div class="field disabled">
                        <label>Bairro</label>
                        <input type="text" name="public_place_company" disabled />
                    </div>
                    <div class="field disabled">
                        <label>Cidade</label>
                        <input type="text" name="city_company" disabled />
                    </div>
                    <div class="field disabled">
                        <label>UF</label>
                        <input type="text" name="state_company" disabled />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>