
<div uk-grid>
    <div class="uk-width-expand@s">
        <div class="ui segment">
            <form class="ui form on-form-security">
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1">
                        <div class="field">
                            <label>Nova senha</label>
                            <input type="password" name="password_user" />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1">
                        <div class="field">
                            <label>Confirmar senha</label>
                            <input type="password" name="cpassword_user" />
                        </div>
                    </div>
                </div>
                <hr class="uk-divider-small" />
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1">
                        <div class="field">
                            <button class="ui primary right labeled icon disabled button">Salvar <i class="ui sign in icon"></i></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>