
         <div class="hero sub">
            <div class="container">
               <div class="hero-title-flex _100">
                  <h1 data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443d9" style="opacity:0" class="display-1 center">Our <span class="title-line">Project</span><br/></h1>
               </div>
               <div class="margin-20px">
                  <div class="we-are-grid">
                     <div>
                        <p data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443e1" style="opacity:0" class="subhead gray">We work with our clients to deliver creative solutions that drive engagement.<strong><br/></strong></p>
                     </div>
                  </div>
               </div>
            </div>
            <div data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443e5" style="opacity:0" class="flex-lottie">
               <a href="#down" data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443e6" class="social-icon down w-inline-block">
                  <div style="-webkit-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="social-circle"></div>
                  <div data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443e8" data-animation-type="lottie" data-src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/6140714b1d7189d6391ea9fc_icons8-down.json" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="1.1666666666666667" data-duration="0" class="animation-image _4"></div>
               </a>
            </div>
            <div class="social-wrapper left">
               <a data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443ea" style="opacity:0" href="https://twitter.com/" target="_blank" class="social-icon w-inline-block">
                  <img src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/61408e584debc11e0c9d4225_facebook.png" loading="lazy" width="20" alt="" class="animation-image"/>
                  <div style="-webkit-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="social-circle"></div>
               </a>
               <a data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443ed" style="opacity:0" href="https://twitter.com/" target="_blank" class="social-icon w-inline-block">
                  <img src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/61408e58412b62ca34cd5219_twitter.png" loading="lazy" width="20" alt="" class="animation-image"/>
                  <div style="-webkit-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="social-circle"></div>
               </a>
               <a data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443f0" style="opacity:0" href="https://twitter.com/" target="_blank" class="social-icon w-inline-block">
                  <img src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/61408e5874d7a635ad9ecf31_instagram.png" loading="lazy" width="20" alt="" class="animation-image"/>
                  <div style="-webkit-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="social-circle"></div>
               </a>
               <a data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443f3" style="opacity:0" href="https://twitter.com/" target="_blank" class="social-icon w-inline-block">
                  <img src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/61408e583ff4391b0bc9191c_linkedin.png" loading="lazy" width="20" alt="" class="animation-image _2"/>
                  <div style="-webkit-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="social-circle"></div>
               </a>
            </div>
         </div>
         <div id="down" data-w-id="f5c767f5-9f72-c1bb-ff41-8c3c492443f6" class="section wf-section">
            <div class="container">
               <div class="w-dyn-list">
                  <div role="list" class="work-grid w-dyn-items">
                      <?php 

                            Zend_Loader::loadClass("Portfolio");
                            $portfolio = new Portfolio();
                            
                            foreach ($portfolio->selectTable() as $value) {
                                echo '<div role="listitem" class="w-dyn-item">
                        <a data-w-id="b92e7673-3985-66b0-fa31-3c0fd629bbe1" style="opacity:0" href="/project/pellentesque-dapibus" class="project-card w-inline-block">
                           <img src="' . $value['image_portfolio'] . '" loading="eager" alt="" class="photo"/>
                           <div data-w-id="b92e7673-3985-66b0-fa31-3c0fd629bbe3" class="project-circle">
                              <div data-w-id="b92e7673-3985-66b0-fa31-3c0fd629bbe4" data-animation-type="lottie" data-src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/6140eb4c33e43849fa9416f0_icons8-eye.json" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="1.1666666666666667" data-duration="0" class="lottie-animation right"></div>
                           </div>
                           <div class="project-overlay">
                              <div class="project-content">
                                 <h3 class="project-ttitle with-px">' . $value['name_portfolio'] . '</h3>
                              </div>
                           </div>
                        </a>
                     </div>';
                           }

                        ?>
                     
                  </div>
               </div>
            </div>
         </div>
         <div data-w-id="663e623e-5ba0-a931-aa30-38ba1c34f4ab" class="section take-off wf-section">
            <div class="container">
               <div class="max-w-width center">
                  <div>
                     <h1 data-w-id="663e623e-5ba0-a931-aa30-38ba1c34f4af" class="display-2">Ready to<span class="title-line _2"> take off?</span></h1>
                  </div>
               </div>
            </div>
            <a href="/contact" class="project-circle black w-inline-block">
               <div data-w-id="663e623e-5ba0-a931-aa30-38ba1c34f4b4" data-animation-type="lottie" data-src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/614461c3fedaa051c5810cd1_icons8-rocket-384.png" data-loop="0" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-duration="0"></div>
               <img src="https://assets.website-files.com/613f528b6c338d2716ac8cbd/6144651fafc60da397af27f5_icons8-rocket-192.png" loading="lazy" alt="" class="lottie-animation right _2"/>
            </a>
         </div>