

<div class="row">
    <div class="column">
        <div class="ui equal width grid on-slider-accounts">
            <div class="row">
                <div class="four wide column">
                    <div class="ui blue segment">
                        <h3 class="uk-h3 uk-margin-remove on-total-accounts">...</h3>
                        <p class="uk-text-meta uk-margin-remove">Cadastros</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
        <div class="ui segment">
            <figure class="highcharts-figure">
                <div id="on-container-in-out">
                    <h4 class="uk-h4 uk-margin-remove uk-text-center">Carregando...</h4>
                </div>
            </figure>
        </div>
    </div>
</div>
